apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo-role
  namespace: developer-project
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
